apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "app.name" . }}-ingress
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: {{ .Values.HostName }}
    http:
      paths:
      - path: /(.*)
        backend:
          serviceName: {{ template "app.name" . }}
          servicePort: 8000