kind: Job
apiVersion: batch/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: db-migrator
spec:
  template:
    spec:
      containers:
      - name: db-migrator
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        command: ["/bin/bash","-c"]
        args: ["python manage.py makemigrations --noinput && python manage.py migrate --noinput"]
      restartPolicy: Never
  backoffLimit: 4
