kind: Job
apiVersion: batch/v1
metadata:
  namespace: test
  name: db-migrator
spec:
  template:
    spec:
      containers:
      - name: db-migrator
        image: revolman/viberr:jenkins_v0.1.3
        command: ["/bin/bash","-c"]
        args: ["python manage.py makemigrations --noinput && python manage.py migrate --noinput"]
      restartPolicy: Never
  backoffLimit: 4
