apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.volumes.persistentVolumeClaim.claimName }}
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storageClassName }}
  accessModes:
    - {{ .Values.accessModes }}
  resources:
    requests:
      storage: {{ .Values.storageSize.storage }}

