apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-env-pvc
  namespace: test
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "200Mi"
