apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: test-viberr
  name: test-viberr
  namespace: test
spec:
  type: NodePort
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: test-viberr
