apiVersion: v1
kind: Service
metadata:
  creationTimestamp: {{ .Values.metadata.creationTimestamp }}
  labels:
    app: "{{ template "app.name" . }}"
  name: "{{ template "app.name" . }}"
  namespace: "{{ .Values.metadata.namespace }}"
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: "{{ template "app.name" . }}"
