kind: Service
apiVersion: v1
metadata:
  name: mysql
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: {{ .Values.Endpoint.ports.port }}
      targetPort: {{ .Values.Endpoint.ports.port }}
      protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql
  namespace: {{ .Release.Namespace }}
subsets:
  - addresses:
      - ip: {{ .Values.Endpoint.addresses.ip }}
    ports:
      - port: {{ .Values.Endpoint.ports.port }}

