apiVersion: v1
kind: Service
metadata:
  creationTimestamp: {{ .Values.metadata.creationTimestamp }}
  labels:
    app: my-nginx
  name: my-nginx
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx
status:
  loadBalancer: {}
