image: "revolman/viberr"
imageTag: "jenkins_v0.1.3"
app: viberr

replicaCount: 1

metadata:
  namespace: test

metadata:
  creationTimestamp: null

strategy:
  type: RollingUpdate

rollingUpdate:
  maxSurge: 1
  maxUnavailable: 0

resources:
  requests:
    cpu: 100m
    memory: 150Mi
  limits:
    cpu: 150m
    memory: 300Mi

volumes:
  persistentVolumeClaim:
    claimName: test-media-pvc

service:
  type: NodePort

storageClassName: managed-nfs-storage
accessModes: ReadWriteMany
storageSize:
  storage: "200Mi"

Endpoint:
  addresses:
    ip: 192.168.0.156
  ports:
    port: 3306
